import type { Ticket, Stats } from './types'

export const tickets: Ticket[] = [
  {
    key: 'RCH-101',
    summary: 'Add export to CSV feature',
    description: 'Users should be able to export their data as a CSV file from the dashboard. The export should include all visible columns and respect any active filters.',
    url: 'https://linear.app/runchise/issue/RCH-101',
    status: 'in_progress',
    stage: 'implement',
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: null,
    prSummary: null,
    startedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    finishedAt: null,
  },
  {
    key: 'RCH-102',
    summary: 'Fix login redirect loop',
    description: 'Some users are experiencing a redirect loop when logging in via SSO. The issue seems related to session cookie handling.',
    url: 'https://linear.app/runchise/issue/RCH-102',
    status: 'blocked',
    stage: 'judge',
    needsHumanCategory: 'missing_context',
    needsHumanReason: 'Requires knowledge of the SSO provider configuration which is not documented in the codebase.',
    prUrl: null,
    prSummary: null,
    startedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    key: 'RCH-103',
    summary: 'Update user profile page design',
    description: 'Redesign the user profile page according to the new Figma mockups. Include avatar upload, theme preference toggle, and notification settings.',
    url: 'https://linear.app/runchise/issue/RCH-103',
    status: 'in_progress',
    stage: 'verify',
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: null,
    prSummary: null,
    startedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    finishedAt: null,
  },
  {
    key: 'RCH-104',
    summary: 'Add pagination to list endpoints',
    description: 'All list endpoints should support cursor-based pagination. Default page size is 20, max is 100.',
    url: 'https://linear.app/runchise/issue/RCH-104',
    status: 'done',
    stage: null,
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: 'https://github.com/runchise/app/pull/447',
    prSummary: 'Added cursor-based pagination to all list endpoints with configurable page size.',
    startedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    key: 'RCH-105',
    summary: 'Implement rate limiting',
    description: 'Add rate limiting to all public API endpoints. Use sliding window algorithm with configurable limits per endpoint.',
    url: 'https://linear.app/runchise/issue/RCH-105',
    status: 'blocked',
    stage: 'implement',
    needsHumanCategory: 'forbidden_path',
    needsHumanReason: 'Attempted to modify auth middleware which is on the blocklist.',
    prUrl: null,
    prSummary: null,
    startedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    key: 'RCH-106',
    summary: 'Add dark mode support',
    description: 'Implement a dark mode theme toggle. Persist preference in localStorage and respect system preference on first visit.',
    url: 'https://linear.app/runchise/issue/RCH-106',
    status: 'backlog',
    stage: null,
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: null,
    prSummary: null,
    startedAt: null,
    finishedAt: null,
  },
  {
    key: 'RCH-107',
    summary: 'Refactor database queries',
    description: 'Optimize slow database queries identified in the latest performance audit. Focus on the dashboard and reporting endpoints.',
    url: 'https://linear.app/runchise/issue/RCH-107',
    status: 'backlog',
    stage: null,
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: null,
    prSummary: null,
    startedAt: null,
    finishedAt: null,
  },
  {
    key: 'RCH-108',
    summary: 'Add audit logging',
    description: 'Implement audit logging for all write operations. Log should include user, action, timestamp, and before/after state.',
    url: 'https://linear.app/runchise/issue/RCH-108',
    status: 'done',
    stage: null,
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: 'https://github.com/runchise/app/pull/452',
    prSummary: 'Added comprehensive audit logging with configurable retention.',
    startedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    finishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    key: 'RCH-109',
    summary: 'Fix timezone display in calendar',
    description: 'Calendar events are showing the wrong time for users in non-UTC timezones. Need to properly convert and display local times.',
    url: 'https://linear.app/runchise/issue/RCH-109',
    status: 'in_progress',
    stage: 'judge',
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: null,
    prSummary: null,
    startedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    finishedAt: null,
  },
  {
    key: 'RCH-110',
    summary: 'Add email notifications',
    description: 'Send email notifications for ticket status changes. Include unsubscribe link and respect user notification preferences.',
    url: 'https://linear.app/runchise/issue/RCH-110',
    status: 'backlog',
    stage: null,
    needsHumanCategory: null,
    needsHumanReason: null,
    prUrl: null,
    prSummary: null,
    startedAt: null,
    finishedAt: null,
  },
]

export const stats: Stats = {
  agentSuccessRate: 0.87,
  avgDurationSec: 483,
  autonomyRate: 0.62,
}

export default { tickets, stats }
